### PR TITLE
Update fnv.zig

### PR DESCRIPTION
**Pull request by chikoYEAT**
fixed wrong multiplier in `self.hash` in fn update()

### CODE REVIEW

**Comment by InKryption** [comment]
Based on the [wikipedia](https://en.wikipedia.org/wiki/Fowler%E2%80%93Noll%E2%80%93Vo_hash_function), wouldn't the more correct thing here be `self.hash = @mulWithOverflow(self.hash, prime)[0];`?

**Comment by chikoYEAT** [comment]
FNV-1 hash algorithm works by:

1. Initializing the hash value with a predefined offset.
2. Iteratively multiplying the hash by a prime 
3. XOR-ing the hash with each byte of the input data.

algorithm uses a prime multiplier (0x100000001b3 for 64-bit FNV-1) in the multiplication step.

**Comment by InKryption** [comment]
Then what exactly is wrong about using `*%=`? At least according to the wikipedia article:
> The [multiply](https://en.wikipedia.org/wiki/Multiply) returns the lower 64-[bits](https://en.wikipedia.org/wiki/Bit) of the [product](https://en.wikipedia.org/wiki/Product_(mathematics)).

And it would seem the zig stdlib's own implementation of fnv does exactly what we currently do. So this change needs better justification.

**Comment by InKryption** [comment]
Justification does not make sense. `*%=` is equivalent to `*=` aside from its behavior on overflow, where the former performs modulo arithmetic, and the latter overflowing is illegal behavior.

**Pull request closed without merging**
