### PR TITLE
feat(ci) add line size checking to the CI

### LINKED ISSUE #359: feat(ci): add CI script that checks that rows are no more than 100 characters

### PR DESCRIPTION
**Pull request by Rexicon226**
closes #359 

My idea with the exclude list is that we'll slowly take files off of it as time goes on. Currently, there are 343 lines in violation left after the current changes. I'll get through the rest of them in a follow-up PR.

Also, excuse the Graphite thing, I was just curious to see what it'd look like. Maybe this could be thought of as a micro-stack lol, where I implement the base feature as one stack, and fix up the lines as a second 🤔 .

I don't think there's much point in going through Graphite right now unless the PR is a much larger feature set than this small tidying PR.

### CODE REVIEW

**Comment by Rexicon226** [comment]
* **#360** <a href="https://app.graphite.dev/github/pr/Syndica/sig/360?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Rexicon226 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by 0xNineteen** [comment]
if we add this to CI, wont we need to fix all of the line lengths so that CI will pass on main (otherwise it will fail and we wont be able to merge anything?)

**Comment by Rexicon226** [comment]
> if we add this to CI, wont we need to fix all of the line lengths so that CI will pass on main (otherwise it will fail and we wont be able to merge anything?)

no, see the exclude list. i don't think it's reasonable to move everything in one go, I'll slowly be moving files over to the new style.

**Review by InKryption — APPROVED** [review]
LGTM, let's get CI back up and running proper

**Review by 0xNineteen — APPROVED** [review]

**Pull request merged**
